apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-unsealer-operator-system
resources:
- https://raw.githubusercontent.com/aamoyel/vault-unsealer-operator/main/deploy/bundle.yml
- vault-keys-secret.yml
- vault-unseal.yml
